# Generated by Django 3.0.8 on 2020-08-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvids',
            name='videoId',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
