# Generated by Django 3.0.8 on 2020-08-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20200813_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedvids',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
